### ISSUE TITLE
manifest erro

### ISSUE THREAD

**Issue by TSCSOftware** [pvsvamsi/Disable-Battery-Optimizations#1]
Attribute application@label value=(LogMate) from AndroidManifest.xml:16:9-32
	is also present at [com.hypertrack:hyperlog:0.0.10] AndroidManifest.xml:12:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:15:4-63:18 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@label value=(LogMate) from AndroidManifest.xml:16:9-32
  	is also present at [com.hypertrack:hyperlog:0.0.10] AndroidManifest.xml:12:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:15:4-63:18 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by cingh-jasdeep** [comment]
I got same error
Launching lib/main.dart on Mi A3 in profile mode...
/Users/Bhujangi/learning/flutter/gpmkc_mobile_app/android/app/src/profile/AndroidManifest.xml:7:9-53 Error:
	Attribute application@label value=(Gurdwara Prabh Milne Ka Chao) from AndroidManifest.xml:7:9-53
	is also present at [com.hypertrack:hyperlog:0.0.10] AndroidManifest.xml:12:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:4:5-54:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processProfileManifest'.
> Manifest merger failed : Attribute application@label value=(Gurdwara Prabh Milne Ka Chao) from AndroidManifest.xml:7:9-53
  	is also present at [com.hypertrack:hyperlog:0.0.10] AndroidManifest.xml:12:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:4:5-54:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 9s
Exception: Gradle task assembleProfile failed with exit code 1
Exited (sigterm)
